### PR TITLE
Stateless schema validator

### LINKED ISSUE #1217: Error calling document.save() more than once in ^0.2.1
Encountering a breaking error when I attempt to call save() on any document type more than once per page load. Refreshing the page resets it. This is only happening in 0.2.1 and higher. Appears to be trying to add the schema more than once?
Screenshot from 2022-02-18 16-41-11

### PR DESCRIPTION
**Pull request by carsonfarmer**
Signed-off-by: Carson Farmer <carson.farmer@gmail.com>

## Description

Fixes #1217

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by awmuncy — APPROVED** [review]

**Comment by statictype** [comment]
Hello! We would love to see this merged if no more approvals are required, it's kind of breaking for our app. Thank you!

**Comment by carsonfarmer** [comment]
I should be able to get this merged today.

**Comment by kwingram25** [comment]
Hello, any progress on this?

**Comment by carsonfarmer** [comment]
Apologies, will force merge and publish tonight/later today. Jumping in now.

**Pull request merged**
